version: "3.8"

services:
    # Сервис для PHP-FPM
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        # ports:
        #     - "8080:80"
        volumes:
            - ./:/var/www/html:rw,delegated
        networks:
            - laravel_network
        depends_on:
            - db
            - redis

    # Веб-сервер Nginx
    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www/html:rw,delegated
            - ./docker/nginx:/etc/nginx/conf.d:ro,delegated
        networks:
            - laravel_network
        depends_on:
            - app

    # База данных MySQL
    db:
        image: postgis/postgis:15-3.3
        container_name: laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ArtDefenderDB
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5433:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel_network

    pgadmin:
        image: dpage/pgadmin4
        container_name: db_interface
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: "zheka.kovylin.7791@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
            - "5050:80"
        networks:
            - laravel_network

    # Redis
    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"
        networks:
            - laravel_network

    # Node.js для сборки фронтенда (опционально)
    node:
        image: node:18
        container_name: laravel_node
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel_network

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
